# Enhanced Mistral-7B Configuration with Checkpointing and Progress Monitoring
# Strategy: Single vLLM server with tensor parallelism + batching + comprehensive checkpointing

questions_file: "/rbstor/ac.ogokdemir/TPC-Paper/astro_radbio_mcqa.json"

model:
  generator:
    generator_type: "vllm"
  
  generator_settings:
    # Traditional fields
    server: "localhost"
    port: 8000
    api_key: "CELS"
    model: "allenai/OLMo-7B-hf"
    temperature: 0.0
    max_tokens: 1024
    
    # Local vLLM server configuration
    boot_local: true
    hf_model_id: "allenai/OLMo-7B-hf"
    auto_port: true
    local_host: "127.0.0.1"
    server_startup_timeout: 600
    
    # vLLM arguments for 8-GPU tensor parallelism
    vllm_args:
      tensor_parallel_size: 4
      max_model_len: 2048
      gpu_memory_utilization: 0.95
      dtype: "auto"
      trust_remote_code: true
      seed: 42
      
      # Performance optimizations for maximum throughput
      pipeline_parallel_size: 1
      max_num_batched_tokens: 16384           # 2x increase for more aggressive batching
      max_num_seqs: 512                       # 2x increase for higher concurrency
      
      # 🔧 CHAT TEMPLATE FIX: Required for transformers v4.44+ with OLMo-7B-hf
      chat_template: "/home/ac.ogokdemir/distllm/examples/miscellaneous/olmo_advanced_chat_template.jinja"
      
    # Request batching configuration - optimized for high throughput
    enable_batching: true
    batch_size: 64                            # Increased for better amortization
    batch_timeout: 1.0                        # Reduced timeout for faster batching
  
  grader_shortname: "gpt-4.1"
  model_config_file: "model_servers.yaml"

rag:
  enabled: false  # Disable for pure generation testing
  use_context_field: false

processing:
  parallel_workers: 8
  question_format: "mc"
  verbose: true
  random_selection: null
  random_seed: 42
  
  # ✨ NEW: Comprehensive Checkpointing and Progress Monitoring
  enable_checkpointing: true              # Enable automatic checkpointing
  checkpoint_interval: 1024                 # Save checkpoint every 50 completed questions
  checkpoint_directory: "/rbstor/ac.ogokdemir/ArgoniumRick/astro-mcqs/baseline/olmo-7b/checkpoints/"     # Directory for checkpoint files
  resume_from_checkpoint: null            # Specify checkpoint file to resume from (null = auto-detect)
  auto_resume: true                       # Automatically resume from latest checkpoint
  progress_bar: true                      # Show progress bar with percentage
  save_incremental: false                 # Ultra-safe mode: save after every question (slower)

output:
  save_incorrect: true
  output_directory: "/rbstor/ac.ogokdemir/ArgoniumRick/astro-mcqs/baseline/olmo-7b"
  output_prefix: "olmo-7b_baseline_checkpointed"

# 🔋 Production Safety Features:
# - Automatic checkpointing every 50 questions
# - Auto-resume from crashes/interruptions  
# - Progress monitoring with percentage completion
# - Memory-safe: doesn't store everything in RAM
# - Crash recovery: can resume from any checkpoint
# - Ultra-safe mode option for critical workloads 