# An input directory containing the files to embed.
input_dir: /rbstor/ac.ogokdemir/ArgoniumRick/RESCUE/jsonls
# An output directory to save the embeddings.
output_dir: /rbstor/ac.ogokdemir/ArgoniumRick/semantic_chunks/rescue/modernbert
# A set of glob patterns to match the input files.
glob_patterns: ['*.jsonl']

# Settings for reading the input files.
dataset_config:
  name: jsonl_chunk
  buffer_size: 4
  batch_size: 16

# Settings for the encoder.
encoder_config:
  name: auto
  pretrained_model_name_or_path: NeuML/bioclinical-modernbert-base-embeddings


# Settings for the pooler.
pooler_config:
  name: mean

# Settings for the embedder.
embedder_config:
  name: semantic_chunk
  chunk_batch_size: 16
  normalize_embeddings: true

# Settings for the writer.
writer_config:
  name: huggingface

# Settings for the parsl compute backend.
compute_config:
  name: workstation
  available_accelerators: ["0", "1", "2", "3", "4", "5", "6", "7"]
