# An input directory containing the files to embed.
input_dir: /lus/eagle/projects/FoundEpidem/braceal/projects/metric-rag/data/parsed_pdfs/LUCID.small.test/parsed_pdfs
# An output directory to save the embeddings.
output_dir: /lus/eagle/projects/FoundEpidem/braceal/projects/metric-rag/data/semantic_chunks/LUCID.small.test.PubMedBERT
# A set of glob patterns to match the input files.
glob_patterns: ['*.jsonl']

# Settings for reading the input files.
dataset_config:
  name: jsonl_chunk
  buffer_size: 4
  batch_size: 512

# Settings for the encoder.
encoder_config:
  name: auto
  pretrained_model_name_or_path: pritamdeka/S-PubMedBert-MS-MARCO

# Settings for the pooler.
pooler_config:
  name: mean

# Settings for the embedder.
embedder_config:
  name: semantic_chunk
  chunk_batch_size: 512

# Settings for the writer.
writer_config:
  name: huggingface

# Settings for the parsl compute backend.
compute_config:
  # The name of the compute platform to use
  name: polaris
  # The number of compute nodes to use
  num_nodes: 1
  # Make sure to update the path to your conda environment and HF cache
  worker_init: "module load conda/2023-10-04; conda activate distllm; export HF_HOME=/lus/eagle/projects/CVD-Mol-AI/braceal/.cache"
  # The scheduler options to use when submitting jobs
  scheduler_options: "#PBS -l filesystems=home:eagle:grand"
  # Make sure to change the account to the account you want to charge
  account: FoundEpidem
  # The HPC queue to submit to
  queue: debug-scaling
  # The amount of time to request for your job
  walltime: 01:00:00
