# This config allows distllm.chat to spawn an interactive chat session.
rag_configs:
  generator_config:
    _target_: ArgoGeneratorConfig
    model: "argo:gpt-4.1"  # Optional, uses env var if not specified
    base_url: "http://lambda5:55625"  # Optional, uses env var if not specified
    temperature: 0.0
    max_tokens: 32768

  retriever_config:
    faiss_config:
      name: faiss_index_v2
      dataset_dir: /homes/ogokdemir/Nov30Demo/semantic_chunks/embeddings/merged
      faiss_index_path: /homes/ogokdemir/Nov30Demo/faiss_indices/sfr_mistral_nmnat
      dataset_chunk_paths: null
      precision: float32
      search_algorithm: exact
      rescore_multiplier: 2
      num_quantization_workers: 1

    encoder_config:
      name: auto
      pretrained_model_name_or_path: "Salesforce/SFR-Embedding-Mistral"

    pooler_config:
      name: last_token

  verbose: false

save_conversation_path: /homes/ogokdemir/Nov30Demo/conversation_logs
