# This config allows distllm.chat to spawn an interactive chat session.
rag_configs:
  generator_config:
    server: rbdgx2
    model: meta-llama/Llama-3.3-70B-Instruct
    port: 9999
    api_key: CELS

  retriever_config:
    faiss_config:
      name: faiss_index_v2
      dataset_dir: /rbstor/ac.ogokdemir/tom_rag/datasets/cancer_merged
      faiss_index_path: /rbstor/ac.ogokdemir/tom_rag/faiss_indices/cancer
      dataset_chunk_paths: null
      precision: float32
      search_algorithm: exact
      rescore_multiplier: 2
      num_quantization_workers: 1

    encoder_config:
      name: auto
      pretrained_model_name_or_path: pritamdeka/S-PubMedBert-MS-MARCO

    pooler_config:
      name: mean

  verbose: false

save_conversation_path: /rbstor/ac.ogokdemir/tom_rag/conversations/cancer
